baseURL = "https://joshgerdes.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Josh Gerdes"
theme = "joshgerdes"

paginate = 12
googleAnalytics = "UA-501066-1"
enableRobotsTXT = true
pygmentsCodefences = true
pygmentsStyle = "monokai"

[taxonomies]
  tag = "tags"

[Permalinks]
  posts = "/:year/:month/:title"

[params]
  author = "Josh Gerdes"
  description = "Founder of Lost Leaf Studio, developer, consultant, cyclist, soccer fan, nature enthusiast and lover of beer."
  recentPostsCount = 5
  summaryLength = 140

[params.social]
  gitHub = "joshgerdes"
  linkedin = "joshgerdes"
  twitter = "joshgerdes"
  instagram = "joshgerdes"
  email   = "josh@joshgerdes.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
